openapi: "3.0.0"
info:
  title: Annotations service
  version: 0.2.0
servers:
  - url: /api/v2private
paths:
  $ref: "./annotationd/_paths.yml"
components:
  parameters:
    $ref: "./annotationd/_parameters.yml"
  schemas:
    $ref: "./annotationd/_schemas.yml"
  responses:
    $ref: "./annotationd/_responses.yml"
