  type: object
  properties:
    clientID:
      type: string
    domain:
      type: string
      format: uri
    redirectURL:
      type: string
      format: uri
    socialSignUpOn:
      type: boolean
    state:
      type: string
