get:
  tags:
    - OAuth
  summary: Get required oauth client variables
  responses:
    '200':
      description: Required OAuth client variables
      content:
        application/json:
          schema:
            $ref: "../schemas/OAuthClientConfig.yml"
    default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "../../common/schemas/Error.yml"
