get:
  summary: Get settings for an org
  parameters:
    - in: path
      name: orgID
      description: org to get settings for
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Current settings for org
      content:
        application/json:
          schema:
            $ref: "../schemas/OrgSettings.yml"
    default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "../../common/schemas/Error.yml"
