  type: object
  properties:
    links:
      type: object
      properties:
        self:
          type: string
          format: uri
    sources:
      type: array
      items:
        $ref: "./Source.yml"
