  type: object
  required:
    - urls
    - token
    - organization
    - bucket
  properties:
    urls:
      type: array
      items:
        type: string
        format: uri
    token:
      type: string
    organization:
      type: string
    bucket:
      type: string
