openapi: "3.0.0"
info:
  title: Influx API Service
  version: 0.1.0
servers:
  - url: /api/v2
paths:
  REF_COMMON_PATHS
components:
  parameters:
REF_COMMON_PARAMETERS
  schemas:
REF_COMMON_SCHEMAS
  responses:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
