openapi: "3.0.0"
info:
  title: Influx API Service
  version: 0.1.0
servers:
  - url: /api/v2
paths:
  REF_COMMON_PATHS
  /users:
    $ref: "./cloud/paths/users.yml"
  "/users/{userID}":
    $ref: "./cloud/paths/users_userID.yml"
  /setup:
    $ref: "./cloud/paths/setup.yml"
  /setup/user:
    $ref: "./cloud/paths/setup_user.yml"
  /authorizations:
    $ref: "./cloud/paths/authorizations.yml"
  /authorizations/{authID}:
    $ref: "./cloud/paths/authorizations_authID.yml"
components:
  parameters:
REF_COMMON_PARAMETERS
  schemas:
REF_COMMON_SCHEMAS
    Resource:
      $ref: "./cloud/schemas/Resource.yml"
    Permission:
      $ref: "./cloud/schemas/Permission.yml"
    User:
      $ref: "./cloud/schemas/User.yml"
    Users:
      $ref: "./cloud/schemas/Users.yml"
    OnboardingResponse:
      $ref: "./cloud/schemas/OnboardingResponse.yml"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
