openapi: "3.0.0"
info:
  title: IDPE-exclusive API endpoints
  version: 2.1.0
servers:
  - url: /api/v2private
paths:
  /oauth/clientConfig:
    $ref: "./cloud/paths/oauth_clientConfig.yml"                
  /limitevents:
    $ref: "./cloud/paths/limitevents.yml"                
  /orgs/{orgID}/limits:
    $ref: "./cloud/paths/orgs_orgID_limits.yml"                
  /orgs/{orgID}/limits/status:
    $ref: "./cloud/paths/orgs_orgID_limits_status.yml"                
  /orgs/{orgID}/settings:
    $ref: "./cloud/paths/orgs_orgID_settings.yml"                
  /tenants:
    $ref: "./cloud/paths/tenants.yml"                
  /setup/user:
    $ref: "./cloud/paths/setup_user.yml"
  # annotationd
  /annotations:
    $ref: "./services/annotationd/paths/annotations.yml"
  /annotations/{annotationID}:
    $ref: "./services/annotationd/paths/annotation.yml"
  /streams:
    $ref: "./services/annotationd/paths/streams.yml"
components:
  schemas:
    OnboardingRequest:
      $ref: "./cloud/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./cloud/schemas/OnboardingResponse.yml"
    InvalidRequestError:
      $ref: "./cloud/schemas/InvalidRequestError.yml"
    UnauthorizedRequestError:
      $ref: "./cloud/schemas/UnauthorizedRequestError.yml"
    ForbiddenRequestError:
      $ref: "./cloud/schemas/ForbiddenRequestError.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
    OAuthClientConfig:
      $ref: "./cloud/schemas/OAuthClientConfig.yml"
    LimitEvent:
      $ref: "./cloud/schemas/LimitEvent.yml"
    LimitEvents:
      $ref: "./cloud/schemas/LimitEvents.yml"
    LimitStatuses:
      $ref: "./cloud/schemas/LimitStatuses.yml"
    LimitStatus:
      $ref: "./cloud/schemas/LimitStatus.yml"
    Limit:
      $ref: "./cloud/schemas/Limit.yml"
    OrgSettings:
      $ref: "./cloud/schemas/OrgSettings.yml"
    OrgSetting:
      $ref: "./cloud/schemas/OrgSetting.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    OrganizationRequest:
      $ref: "./cloud/schemas/OrganizationRequest.yml"
    # annotationd
    AnnotationListFilter:
      $ref: "./services/annotationd/schemas/AnnotationListFilter.yml"
    AnnotationDeleteFilter:
      $ref: "./services/annotationd/schemas/AnnotationDeleteFilter.yml"
    BasicFilter:
      $ref: "./services/annotationd/schemas/BasicFilter.yml"
    AnnotationList:
      $ref: "./services/annotationd/schemas/AnnotationList.yml"
    AnnotationCreateList:
      $ref: "./services/annotationd/schemas/AnnotationCreateList.yml"
    AnnotationCreate:
      $ref: "./services/annotationd/schemas/AnnotationCreate.yml"
    Annotation:
      $ref: "./services/annotationd/schemas/Annotation.yml"
    StreamListFilter:
      $ref: "./services/annotationd/schemas/StreamListFilter.yml"
    StreamDeleteFilter:
      $ref: "./services/annotationd/schemas/StreamDeleteFilter.yml"
    StreamList:
      $ref: "./services/annotationd/schemas/StreamList.yml"
    Stream:
      $ref: "./services/annotationd/schemas/Stream.yml"
    ReadStream:
      $ref: "./services/annotationd/schemas/ReadStream.yml"
  parameters:
    # annotationd
    AnnotationListFilter:
      $ref: "./services/annotationd/parameters/AnnotationListFilter.yml"
    AnnotationDeleteFilter:
      $ref: "./services/annotationd/parameters/AnnotationDeleteFilter.yml"
    StreamListFilter:
      $ref: "./services/annotationd/parameters/StreamListFilter.yml"
    StreamDeleteFilter:
      $ref: "./services/annotationd/parameters/StreamDeleteFilter.yml"
  responses:
    # annotationd
    NoContent:
      $ref: "./common/responses/NoContent.yml"
    BadRequest:
      $ref: "./common/responses/BadRequest.yml"
    Unauthorized:
      $ref: "./common/responses/Unauthorized.yml"
    NotAllowed:
      $ref: "./common/responses/NotAllowed.yml"
    ServerError:
      $ref: "./common/responses/ServerError.yml"
