openapi: "3.0.0"
info:
  title: Influx API Service
  version: 0.1.0
servers:
  - url: /api/v2
paths:
REF_COMMON_PATHS
  /health:
    $ref: "./oss/paths/health.yml"
  /ready:
    $ref: "./oss/paths/ready.yml"
  /users:
    $ref: "./oss/paths/users.yml"
  "/users/{userID}":
    $ref: "./oss/paths/users_userID.yml"
  /setup:
    $ref: "./oss/paths/setup.yml"
  /setup/user:
    $ref: "./oss/paths/setup_user.yml"
  /authorizations:
    $ref: "./oss/paths/authorizations.yml"
  /authorizations/{authID}:
    $ref: "./oss/paths/authorizations_authID.yml"
components:
  parameters:
REF_COMMON_PARAMETERS
  schemas:
REF_COMMON_SCHEMAS
    Authorization:
      $ref: "./oss/schemas/Authorization.yml"
    Authorizations:
      $ref: "./oss/schemas/Authorizations.yml"
    Permission:
      $ref: "./oss/schemas/Permission.yml"
    Resource:
      $ref: "./oss/schemas/Resource.yml"
    User:
      $ref: "./oss/schemas/User.yml"
    Users:
      $ref: "./oss/schemas/Users.yml"
    OnboardingResponse:
      $ref: "./oss/schemas/OnboardingResponse.yml"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
