openapi: "3.0.0"
info:
  title: Influx API Service
  version: 0.1.0
servers:
  - url: /api/v2
paths:
  $ref: "./common/_paths.yml"
components:
  parameters:
    $ref: "./common/_parameters.yml"
  schemas:
    $ref: "./common/_schemas.yml"
  responses:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
