openapi: 3.0.0
info:
  title: Cloud Data Sources Service
  version: '1.0'
servers:
  - url: /
paths:
  /datasources:
    $ref: ./svc/cloud-data-sources/paths/datasources.yml
  '/datasources/{datasourceID}':
    $ref: ./svc/cloud-data-sources/paths/datasources-id.yml
  '/webhooks/{token}':
    $ref: ./svc/cloud-data-sources/paths/webhooks.yml
components:
  schemas:
    Datasource:
      $ref: ./svc/cloud-data-sources/schemas/Datasource.yml
    ListenerEndpoint:
      $ref: ./svc/cloud-data-sources/schemas/ListenerEndpoint.yml
    Service:
      $ref: ./svc/cloud-data-sources/schemas/Service.yml
