openapi: 3.0.1
info:
  title: flowd api
  version: 0.0.0
servers:
  - url: '/'
paths:
  /flows/orgs/{orgID}/flows:
    $ref: "./svc/flowd/paths/flows_orgs_orgID_flows.yml"
  /flows/orgs/{orgID}/flows/{id}:
    $ref: "./svc/flowd/paths/flows_orgs_orgID_flows_id.yml"
components:
  schemas:
    ProtobufAny:
      $ref: "./svc/flowd/schemas/ProtobufAny.yml"
    RuntimeError:
      $ref: "./svc/flowd/schemas/RuntimeError.yml"
    Flow:
      $ref: "./svc/flowd/schemas/Flow.yml"
    FlowCreateRequest:
      $ref: "./svc/flowd/schemas/FlowCreateRequest.yml"
    FlowList:
      $ref: "./svc/flowd/schemas/FlowList.yml"
    FlowUpdateRequest:
      $ref: "./svc/flowd/schemas/FlowUpdateRequest.yml"
