openapi: 3.1.0
info:
  title: Cloud Data Sources Service
  version: '1.0'
servers:
  - url: /
paths:
  '/orgs/{orgID}/datasources':
    $ref: ./svc/cloud-data-sources/paths/datasources.yml
  '/orgs/{orgID}/datasources/{datasourceID}':
    $ref: ./svc/cloud-data-sources/paths/datasource.yml
components:
  schemas:
    Datasource:
      $ref: ./svc/cloud-data-sources/schemas/Datasource.yml
    ListenerEndpoint:
      $ref: ./svc/cloud-data-sources/schemas/ListenerEndpoint.yml
    Service:
      $ref: ./svc/cloud-data-sources/schemas/Service.yml
  responses:
    NoContent:
      $ref: ./common/responses/NoContent.yml
    ServerError:
      $ref: ./common/responses/ServerError.yml
